import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from helper import scroll_page

def knowledge(driver):
    knowledge = driver.find_element(*(By.XPATH,"//a[normalize-space()='Knowledge']")).click()
    time.sleep(2)
    cdsc = driver.find_element(*(By.XPATH,"//a[normalize-space()='Registered Companies CDSC']"))
    c_asba = driver.find_element(*(By.XPATH,"//a[normalize-space()='Registered C-ASBA BFIs']"))
    dp_list = driver.find_element(*(By.XPATH,"//a[normalize-space()='Licensed DP List']"))
    asba_members = driver.find_element(*(By.XPATH,"//a[normalize-space()='ASBA Member BFIS']"))
    merchant_bankers = driver.find_element(*(By.XPATH,"//li[@class='has-sub']//ul//li//a[normalize-space()='Merchant Bankers']"))
    share_registers = driver.find_element(*(By.XPATH,"//a[normalize-space()='Share Registrars']"))
    credit_ratings = driver.find_element(*(By.XPATH,"//a[normalize-space()='Credit Ratings']"))
    brokers_list = driver.find_element(*(By.XPATH,"//li[@class='has-sub']//ul//li//a[normalize-space()='Broker List']"))
    commercial_banks = driver.find_element(*(By.XPATH,"//a[normalize-space()='Commercial Banks']"))
    insurance_companies = driver.find_element(*(By.XPATH,"//a[normalize-space()='Insurance Companies']"))
    # guide_part_1 = driver.find_element(*By.XPATH,"//a[normalize-space()='Part 1']")
    video_tutorials = driver.find_element(*(By.XPATH,"//a[normalize-space()='Video Tutorials']"))
    investment_summit = driver.find_element(*(By.XPATH,"//a[normalize-space()='Investment Summit 2019']"))
    tax_for_bonus_list = driver.find_element(*(By.XPATH,"//a[normalize-space()='Tax for Bonus List']"))

    actions = ActionChains(driver)
    actions.move_to_element(cdsc).move_to_element(c_asba).click().perform()
    time.sleep(2)
    scroll_page(driver)
    driver.find_element(by=By.TAG_NAME, value="body").send_keys(Keys.PAGE_UP)
    time.sleep(2)
    entries = driver.find_element(*(By.XPATH,"//select[@name='myTable_length']"))
    entries.click()
    time.sleep(2)
    actions.send_keys(Keys.ARROW_DOWN + Keys.ENTER).perform()
    time.sleep(1)
    scroll_page(driver)
    page_2 = driver.find_element(*(By.XPATH,"//a[normalize-space()='2']"))
    page_2.click()
    time.sleep(2)
    driver.find_element(by=By.TAG_NAME, value="body").send_keys(Keys.PAGE_UP + Keys.PAGE_UP + Keys.PAGE_UP)
    time.sleep(2)
    driver.execute_script("document.body.style.zoom = '0.5';")
    driver.save_screenshot("C:\\Users\\rabee\\Desktop\\selenium\\SS3.png")
    time.sleep(2)
    driver.back()   


    actions.move_to_element(insurance_companies).move_to_element(commercial_banks).move_to_element(brokers_list).move_to_element(credit_ratings).click().perform()
    time.sleep(2)
    entry = driver.find_element(*(By.XPATH,"//select[@name='myTableIc_length']"))
    entry.click()
    time.sleep(1)
    actions.send_keys(Keys.ARROW_DOWN + Keys.ENTER).perform()
    time.sleep(1)
    scroll_page(driver)
    time.sleep(1)
    driver.find_element(by=By.TAG_NAME, value="body").send_keys(Keys.PAGE_UP + Keys.PAGE_UP + Keys.PAGE_UP)
    time.sleep(2)
    care_rating = driver.find_element(*(By.XPATH,"//a[normalize-space()='Care Rating']"))
    care_rating.click()
    time.sleep(1)
    entry1 = driver.find_element(*(By.XPATH,"//select[@name='myTableCr_length']"))
    entry1.click()
    time.sleep(1)
    actions.send_keys(Keys.ARROW_DOWN + Keys.ENTER).perform()
    time.sleep(1)
    scroll_page(driver)
    time.sleep(1)
    driver.find_element(by=By.TAG_NAME, value="body").send_keys(Keys.PAGE_UP + Keys.PAGE_UP + Keys.PAGE_UP)
    time.sleep(5)

